### ISSUE TITLE
ES2015ify

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/meta#15]
We should ES2015ify all our repos and require Node.js 4. Also bump all dependencies while we're at it. We've already done many repos, but I think there's still some left.

Example: https://github.com/imagemin/zopflipng-bin/commit/87f9f4520270ffd6ce0689c87f139469eff9e36b

Anyone wanna take this on?

// @shinnn @1000ch

**Comment by 1000ch** [comment]
I'll do 👌

**Comment by sindresorhus** [comment]
Awesome! Make sure you only use features available in Node.js 4, meaning no destructuring or rest/spread.

**Comment by 1000ch** [comment]
Would you review PRs 👆 if you have time?

**Comment by sindresorhus** [comment]
Great work @1000ch. Sorry for my slow review time.

**Comment by sindresorhus** [comment]
@1000ch Is this done for all the repos?

**Comment by 1000ch** [comment]
@sindresorhus Seems to be done.
