### ISSUE TITLE
Use AVA

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/meta#16]
Would be nice to use AVA on all our repos instead of Mocha, as it makes it a lot easier to do async tests.

Should do https://github.com/imagemin/meta/issues/15 first, or at the same time, as AVA requires Node.js 4.

**Comment by bradbaris** [comment]
Related to avajs/ava#1354, AVA now requires Node>=4.5, so we might need to change something about the Node 4 requirement.

**Comment by sindresorhus** [comment]
@bradbaris No. AVA is a devDependency.

**Comment by sindresorhus** [comment]
@1000ch Is this now done on all the repos?

**Comment by 1000ch** [comment]
@sindresorhus Seems to be done.
