### ISSUE TITLE
gif2webp bin

### ISSUE THREAD

**Issue by skylve** [imagemin/meta#17]
I see [github.com/imagemin](github.com/imagemin) is hosting many `bin-wrapper` for images (nice module btw).
I was wondering if you thought of adding `gif2webp` bin ? (since you already have `cwebp`).

I feel it is better that a github organization like github.com/imagemin host this repo (I would gladly PR to it if you need).

**Comment by sindresorhus** [comment]
I think it makes sense. Imagemin's mission is to reduce the size of images, and GIFs are the worst offenders, so converting to WebP is a kind of minifying. @shinnn @1000ch Thoughts?

**Comment by 1000ch** [comment]
👍 
WebP animation is completely better than GIF's one at various points.

**Comment by shinnn** [comment]
👍 WebP seems smaller and smoother generally. http://littlesvr.ca/apng/gif_apng_webp.html

**Comment by sindresorhus** [comment]
@1000ch @shinnn Do either of you want to do it? Or should we tell @skylve "PR welcome"?

**Comment by 1000ch** [comment]
@skylve @sindresorhus Now available. 
https://github.com/imagemin/gif2webp-bin
https://github.com/imagemin/imagemin-gif2webp

**Comment by sindresorhus** [comment]
@1000ch Great! Can you add them to the npm org? (See; https://github.com/imagemin/meta/issues/14)

**Comment by 1000ch** [comment]
@sindresorhus Done ✅  https://www.npmjs.com/org/imagemin

**Comment by skylve** [comment]
@1000ch Thanks ! Greatly appreciate ;)
