### ISSUE TITLE
Move repos

### ISSUE THREAD

**Issue by kevva** [imagemin/meta#3]
Move all imagemin affiliated repos to this organization.

**Comment by sindresorhus** [comment]
Remember to update all references in those repos ;)

**Comment by kevva** [comment]
Going to `sed` my way out of it.

**Comment by sindresorhus** [comment]
I usually `ag` myself out of things.

**Comment by shinnn** [comment]
It's OK to move [imagemin-jpeg-recompress](https://github.com/shinnn/imagemin-jpeg-recompress) repository to this organization.

**Comment by kevva** [comment]
@shinnn, feel free :).

**Comment by shinnn** [comment]
Done. [imagemin/imagemin-jpeg-recompress](https://github.com/imagemin/imagemin-jpeg-recompress)

**Comment by kevva** [comment]
Could you also give npm access?

**Comment by shinnn** [comment]
I added @kevva and @sindresorhus as owners. www.npmjs.org/package/imagemin-jpeg-recompress

**Comment by kevva** [comment]
Sweetness :D! Thank you!

**Comment by sindresorhus** [comment]
Thank you @shinnn :)

**Comment by kevva** [comment]
@1000ch, could you transfer the rest of the bin-wrappers too?

**Comment by 1000ch** [comment]
@kevva I transferred rest of them.

**Comment by kevva** [comment]
Except the cwebp one :D. I want to fix that since it's currently broken. Thank you though!

**Comment by shinnn** [comment]
> Except the cwebp one :D. I want to fix that since it's currently broken.

I fixed the build error. https://travis-ci.org/1000ch/node-cwebp-bin/builds/34561947

**Comment by kevva** [comment]
@1000ch, need to publish new version of cwebp-bin to npm.

**Comment by 1000ch** [comment]
@kevva Sorry, published and add you as npm owners.

**Comment by kevva** [comment]
Cool, thanks :)!

**Comment by shinnn** [comment]
All imagemin-related repos seem to have been moved here.
