### ISSUE TITLE
Add "gulpplugin" keyword to the imagemin plugins

### ISSUE THREAD

**Issue by shinnn** [imagemin/meta#6]
Is it possible?

cf. https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

**Comment by kevva** [comment]
+1, go for it!

**Comment by shinnn** [comment]
@kevva Yeah, I want to do that.

@contra

Sorry to bother you.
Can we add _gulpplugin_ keyword to a module whose name doesn't start with `gulp-`?

Imagemin plugins (e.g. [imagemin-mozjpeg](https://github.com/imagemin/imagemin-mozjpeg/blob/master/index.js)) handle vinyl files using through2 and [can be used as gulp plugin](https://github.com/imagemin/imagemin-mozjpeg#usage).

**Comment by yocontra** [comment]
@shinnn yup

**Comment by shinnn** [comment]
@contra Thanks for your quick response :)

**Comment by shinnn** [comment]
Done.
